### ISSUE TITLE
Move hardcoded String to String Resources

### ISSUE THREAD

**Issue by wilder** [WilderPereira/Reciclo#7]

**Comment by the7th** [comment]
Can you elaborate more on this? Thanks! Found this through Hacktoberfest

**Comment by wilder** [comment]
In many parts of the code you can find hardcoded strings that should either be in the res/values/strings.xml or that should be a constant (you can choose for what you think is better for the case). 

For example:
```
setTextInputLayoutError(textInputLayout, "extract me to resources!")
```
the String `"extract me to resources!"` should be in the strings.xml file and should be used like this:

`setTextInputLayoutError(textInputLayout, getString(R.string.password_empty))`

[This answer](https://stackoverflow.com/a/39130143/4872155) on StackOverflow can make it easier to find all the occurrences of hardcoded strings in the code

**Comment by the7th** [comment]
alright. will help doing this tonight if I'm free. :)

**Comment by wilder** [comment]
Nice, thank you!

**Comment by manmeet-22** [comment]
I will work on it once the Hacktober starts. :)

**Comment by divyangshah97** [comment]
I pulled ur code , it has a google-services plugin which needs a google-services.json file . According to me , this file is required to connect to firebase , do i need to connect your project to firebase

**Comment by Raman1121** [comment]
I would also like to work on this!
@WilderPereira

**Comment by ngengesenior** [comment]
I would like to work on this as well @WilderPereira

**Comment by praveenkannan** [comment]
Woah! I am in for this. @WilderPereira

**Comment by wilder** [comment]
@jonathanrandev worked on hardcoded strings from the xml layout files, but there are still some hardcoded strings in the Java code, so I'll leave this issue opened.

**Comment by manmeet-22** [comment]
Hey @WilderPereira  just cloned your project. it requires a google-services.json file. You should have used firebase in your app. If you can provide it.

**Comment by jonathanrandev** [comment]
@WilderPereira, log messages should not be added to the string resource files, am i right?
So far after going through the code, I've only seen hard-coded strings for the firebase real time database and log messages. Any thing particular that you have in mind?
